name = "placeholders-dev"
workers_dev = true
compatibility_date = "2023-03-07"
main = "./workers-site/index.js"
node_compat = true

[site]
bucket = "./public"

[env.staging]
name = "placeholders-staging"
workers_dev = true
node_compat = true

[env.production]
name = "placeholders"
workers_dev = false
routes = [
	{pattern = "placeholders.cmer.eu.org/*", zone_id = "f5d4e94cb23f69f8ae69baedff94f2ba"},
	{pattern = "placeholderimgs.cmer.eu.org/*", zone_id = "f5d4e94cb23f69f8ae69baedff94f2ba"}
]
node_compat = true
